apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maskani
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - v1.sandbox.maskani.co.ke
    - www.v1.sandbox.maskani.co.ke
    secretName: maskani-tls
  rules:
    - host: v1.sandbox.maskani.co.ke
      http:
        paths:
        - path: /
          backend:
            serviceName: maskani
            servicePort: 3000
    - host: www.v1.sandbox.maskani.co.ke
      http:
        paths:
        - path: /
          backend:
            serviceName: maskani
            servicePort: 3000
