apiVersion: v1
kind: Service
metadata:
  name: maskani
  labels:
    app:  core
    tier: backend
    type: app
    name: maskani
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: core
    tier: backend
    type: app
    name: maskani